### ISSUE TITLE
Problems with Visual Studio and Enet.dll

### ISSUE THREAD

**Issue by Ollie-cj** [nxrighthere/ENet-CSharp#53] opened 2019-03-05 14:18 UTC
Hi there,

Excited to give this library a whirl but I'm struggling with Nuget installation; I'm getting the following error with Enet.dll:

'Please make sure that the file is accessible and that it is a valid assembly or COM component.'

From what I understand this is to do with using unmanaged libraries in a managed project, I'm probably missing a simple necessary step so apologies if this is a noobie question.

**Comment by nxrighthere** [comment] 2019-03-05 14:29
Which .NET version/runtime are you using?

**Comment by Ollie-cj** [comment] 2019-03-05 14:37
4.7.1 - If this is the issue is there any way of referencing ENet.dll in this version? If not, which version whould I be running?

**Comment by nxrighthere** [comment] 2019-03-05 14:55
The libraries are compiled only for the x64 architecture, so if you are running x86 they will not work. I tried to use the package with 4.7.2, and everything works fine on my side.

**Comment by nxrighthere** [comment] 2019-03-05 14:56
By the way, you can't reference the native library in your project, you should use only the managed assemblies. The native library will be loaded automatically.

**Comment by nxrighthere** [comment] 2019-03-05 14:57
In your case you only need to reference `ENet-CSharp.dll`.

**Comment by Ollie-cj** [comment] 2019-03-05 14:58
That's what I did initially, whenever I run a project I receive the following error (on the line ENet.Library.Initialize();)

System.DllNotFoundException: 'Unable to load DLL 'enet': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

**Comment by Ollie-cj** [comment] 2019-03-05 15:14
I'm upgrading to 4.7.2 now - I'll let you know how I get on!

Thanks for your prompt answers - if you can think of any other solutions I'm all ears

**Comment by nxrighthere** [comment] 2019-03-05 15:19
> System.DllNotFoundException: 'Unable to load DLL 'enet': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

Make sure that the native library is placed into the same folder with the managed assembly.

**Comment by Ollie-cj** [comment] 2019-03-05 15:39
It is, along with the .dylib and .so files, and I still receive the not found error.

Unfortunately I'm also getting the same error as before in 4.7.2, When I install the package through NuGet I receive the message:

Failed to add reference to 'enet'.
Please make sure that the file is accessible, and that it is a valid assembly or COM component.		

The package then uninstalls, I'm running Visual Studio 2017 (Community) and have tried this on two computers, so I'm not entirely sure what's going wrong. The build mode is set to Debug x64

**Comment by nxrighthere** [comment] 2019-03-05 15:41
Can you check how it works with .NET Core for you using dotnet toolchain?

**Comment by nxrighthere** [comment] 2019-03-05 16:24
It seems that I should restructure the files in the NuGet package a bit for Visual Studio, I think I've found where the problem is...

**Comment by Ollie-cj** [comment] 2019-03-05 16:28
Amazing - thanks 👍  

Haven't had much joy with Core:

C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'C:\Users\USER\myApp\packages\enet\enet.dll' could not be opened -- PE image doesn't contain managed metadata. [C:\Users\USER\myApp\myApp.csproj]

Despite the same manual referencing:

  <ItemGroup>
    <Reference Include="ENet">
      <HintPath>\packages\enet\ENet-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

Can only imagine it's the same error? Eagerly awaiting the update

**Comment by nxrighthere** [comment] 2019-03-05 19:04
Can you check how it works now?

**Comment by nxrighthere** [comment] 2019-03-05 20:12
I think I need to make one more change...

**Comment by nxrighthere** [comment] 2019-03-05 20:18
Funny, I fixed this for Visual Studio, but these changes break compatibility with dotnet toolchain that targets .NET Core.

**Comment by nxrighthere** [comment] 2019-03-05 20:21
No idea how to make them both happy, here's the package that should be compatible with Visual Studio.

[ENet-NuGet.2.2.0.zip](https://github.com/nxrighthere/ENet-CSharp/files/2932694/ENet-NuGet.2.2.0.zip)

**Comment by Ollie-cj** [comment] 2019-03-06 13:43
That package works a treat for me - thank you! Best of luck working out the compatibility issues, in the meantime thanks once again.

**Comment by nxrighthere** [comment] 2019-03-06 14:40
Glad to hear, I'll try to fix compatibility issues a bit later. For now just use this package please.

**Comment by nxrighthere** [comment] 2019-03-07 15:00
This should be fixed in 2.2.1 version. NuGet package indexing will take time for the new version.

**Closed by nxrighthere** 2019-03-07 15:00 UTC
Labels: distribution, help wanted
